### ISSUE TITLE
Terminar models

### ISSUE THREAD

**Issue by lCh3z** [lCh3z/CPSITeM_API#39]
Deberán diseñar los modelos que se especifican más adelante, siguiendo el formato que tienen los modelos ya creados (User, Worker, Order, etc.). Para esto también se tienen que hacer modificaciones a los controladores (tambien pueden revisar los controladores de los modelos antes mencionados) para que funcione correctamente. Todos los modelos deben agregarse a models/index.js.
Estos son los modelos restantes:
 - [x] Product
 - [x] Notification
 - [x] NewList
 - [x] StatService
 - [x] ImgStatService
 - [x] Category
 - [x] ImgProduct
 - [x] Cuppon
 - [x] Address
 - [x] Payment
 - [x] Configuration
 - [x] Section
 - [x] ConfSection

**Comment by UlisesMarcos** [comment]
end

**Comment by Oscar98** [comment]
fin
