### ISSUE TITLE
Implementar un middleware para validar requests

### ISSUE THREAD

**Issue by lCh3z** [lCh3z/CPSITeM_API#76]
Este debe permitir hacer multiples tipos de validaciónes a los campos que se reciben en el body y los params. Validar lo siguiente:
 - [x] word
 - [x] integer
 - [x] unsigned
 - [x] email
 - [x] rfc
 - [x] file
 - [x] min
 - [x] max
 - [x] length
 - [x] unique
 - [x] bigger
 - [x] lower
 - [x] equal
 - [x] bigger_equal
 - [x] lower_equal

**Comment by dartrox21** [comment]
Finalizado :)
